//authentication
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

//children
export const SET_CURRENT_CHILD = 'SET_CURRENT_CHILD'
export const CHILDREN_FETCH_DATA = 'CHILDREN_FETCH_DATA'
export const CHILDREN_LOAD_DATA = 'CHILDREN_LOAD_DATA'
export const CHILDREN_WILL_POST = 'CHILDREN_WILL_POST'
export const CHILDREN_ADD_DATA = 'CHILDREN_ADD_DATA';
export const CHILDREN_DELETE_DATA = 'CHILDREN_DELETE_DATA';

//feeding 
export const FEEDING_FETCH_DATA = 'FEEDING_FETCH_DATA'
export const FEEDING_LOAD_DATA = 'FEEDING_LOAD_DATA'
export const FEEDING_POST_DATA = 'FEEDING_POST_DATA'

//sleep
export const SLEEP_FETCH_DATA = 'SLEEP_FETCH_DATA'
export const SLEEP_LOAD_DATA = 'SLEEP_LOAD_DATA'

//diaper
export const DIAPER_LOAD_DATA = 'DIAPER_LOAD_DATA'

//misc
export const CLEAR_DATA = 'CLEAR_DATA'