//authentication
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS'
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'

//children
export const SET_CURRENT_CHILD = 'SET_CURRENT_CHILD'
export const CHILDREN_LOAD_DATA = 'CHILDREN_LOAD_DATA'
export const CHILD_FORM_EDIT = 'CHILD_FORM_EDIT'
export const CHILD_FORM_CLEAR = 'CHILD_FORM_CLEAR'

export const SLEEP_LOAD_DATA = 'SLEEP_LOAD_DATA'
export const DIAPER_LOAD_DATA = 'DIAPER_LOAD_DATA'
export const CLEAR_DATA = 'CLEAR_DATA'