apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: null
    generation: 1
    labels:
      run: goparentgui
    name: goparentgui
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/goparentgui
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: goparentgui
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: goparentgui
      spec:
        containers:
        - image: goparentgui:v0.16
          imagePullPolicy: IfNotPresent
          name: goparentgui
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      run: goparentgui
    name: goparentgui
    selfLink: /api/v1/namespaces/default/services/goparentgui
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      run: goparentgui
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""